### ISSUE TITLE
Looking for commit access

### ISSUE THREAD

**Issue by jamiecook** [vnopenroads/openroads-vn-api#9]
Hi all, @geohacker ?
I'm currently working on integrating some components of CBA into ORMA and believe I'll probably need access to this repo. 

Who is currently maintaining this repo and can help with that?
Also is there documentation on how this is currently deployed?

**Comment by geohacker** [comment]
Hi @jamiecook, I've not been working on this project since 2019 when our contract ended. I don't think anyone is actively maintaining it. I also don't have enough access to give you push access to this repo. Unfortunately I won't be of much help. Sorry!

**Comment by jamiecook** [comment]
Thanks @geohacker  - maybe it's @tailm1 i need to follow up with.

**Comment by tailm1** [comment]
hi @ngdnghia28  plz follow up and support @jamiecook

**Comment by ngdnghia28** [comment]
@jamiecook 
I required to deploy system in local provider instead of using AWS. So deployment is changed too.


> Also is there documentation on how this is currently deployed?

We don't have document yet. For brief:
- We use 2 VMs to deploy system
  - 1 for DB
  - 1 for API, cronjob, etc
- All VM can access by ssh to the servers
- CI/CD: we don't have this yet. So if you want to deploy you need to request @tailm1 

I think if you need to deploy new service it is better to create a new VM.

**Comment by jamiecook** [comment]
@ngdnghia28  - okay, that is noted. 
Can you provide commit access here?

Also - is there database backups in use?

**Comment by jamiecook** [comment]
Hi @ngdnghia28  - can you provide developer access (create merge requests, branches, etc)?

**Comment by ngdnghia28** [comment]
PRs:
- https://github.com/vnopenroads/openroads-vn-tiler/pull/1
- https://github.com/vnopenroads/openroads-vn-analytics/pull/12
- https://github.com/vnopenroads/openroads-vn-tilemap/pull/9
- https://github.com/vnopenroads/openroads-vn-analytics/pull/12

New repo:
- https://github.com/vnopenroads/serve-mbtiles

**Comment by ngdnghia28** [comment]
@jamiecook Please request @tailm1 
So I can give you DB connection, etc.

**Comment by jamiecook** [comment]
@ngdnghia28 - i already have sufficient DB connections etc - i just need the ability to create PRs in this (and other repos)

![image](https://user-images.githubusercontent.com/151124/125866103-13103096-0677-4562-ad99-3e13e14b6c63.png)

**Comment by jamiecook** [comment]
That's great, thanks @ngdnghia28. I will respect the responsibility I've been given.
